default: &default
  adapter: postgresql
  pool: 8
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: photo_store_development
  username: omnistream
  password: omnistream
  host: localhost
  port: 5432
  min_messages: WARNING

test:
  <<: *default
  database: photo_store_test
  username: omnistream
  password: omnistream
  host: localhost
  port: 5432
  min_messages: WARNING

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || (ENV['RAILS_MAX_THREADS'].try { |n| n.to_i + 3 }) || 5 %>
