# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc4150e24be48985d17588fe4e46a7841ad43840435414a31754238e493ecd668a1fbaec5de9cff8e3f9165a4643dc0c84f22b4fb6e67edeed06363db1b8385b

test:
  secret_key_base: 73213437accbaa42ef7440aa686f59f78bb83b38d49cbc5cc1a4e59ff3eb6380cbff8a2ae7731f37a1d0e07b7b67883b873c359cd0811e7aff873f5f5b6de559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
